version: '3'

tasks:
  install:
    cmds:
      - deno install

  lint:
    cmds:
      - deno fmt

  test:
    cmds:
      - deno test src/

  dev:
    cmds:
      - deno serve -R src/main.ts

  emoji:
    cmds:
      - deno run cmd/emoji.ts

  ksuid:
    cmds:
      - deno run cmd/ksuid.ts

  amqp:
    cmds:
      - deno run --allow-read --allow-net --allow-env  cmd/amqp.ts
